version: "3.9"

services:
  backend:
    build: ./back-end
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env

  frontend:
    build: ./front-end
    ports:
      - "4173:4173"
    depends_on:
      - backend
